### ISSUE TITLE
Discuss how to disperse siblings

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/disperse-siblings-simulator#1]
I write a notebook to simulate the review of siblings in Anki: https://github.com/open-spaced-repetition/disperse-siblings-simulator/blob/main/notebook.ipynb

Assuming there are 4 siblings of the same note, here is a typical schedule of Anki:

```
Day 0	L card:0  R=100.00% grade:1  ivl:  1 (  1, 1  )	next due:  1
Day 1	R card:0  R= 83.98% grade:3  ivl:  3 (  2, 4  )	next due:  4
Day 2	L card:1  R=100.00% grade:2  ivl:  1 (  1, 1  )	next due:  3
Day 3	R card:1  R= 91.79% grade:3  ivl:  3 (  2, 6  )	next due:  7
Day 4	R card:0  R= 88.43% grade:3  ivl:  9 (  6, 10 )	next due: 12
Day 5	L card:2  R=100.00% grade:4  ivl:  6 (  6, 10 )	next due: 13
Day 6	L card:3  R=100.00% grade:1  ivl:  1 (  1, 1  )	next due:  7
Day 7	R card:1  R= 89.55% grade:3  ivl: 13 ( 10, 14 )	next due: 19	R card:3  R= 83.98% grade:3  ivl:  3 (  2, 4  )	next due: 10
Day 10	R card:3  R= 88.43% grade:3  ivl:  9 (  6, 10 )	next due: 18
Day 12	R card:0  R= 89.74% grade:3  ivl: 21 ( 17, 23 )	next due: 32
Day 13	R card:2  R= 89.97% grade:3  ivl: 28 ( 28, 34 )	next due: 44
Day 18	R card:3  R= 89.74% grade:3  ivl: 22 ( 17, 23 )	next due: 38
Day 19	R card:1  R= 90.29% grade:3  ivl: 33 ( 32, 38 )	next due: 54
Day 32	R card:0  R= 90.12% grade:1  ivl:  3 (  2, 4  )	next due: 35
Day 35	R card:0  R= 91.12% grade:3  ivl:  5 (  5, 9  )	next due: 42
Day 38	R card:3  R= 90.12% grade:3  ivl: 50 ( 46, 52 )	next due: 87
Day 42	R card:0  R= 89.81% grade:3  ivl: 16 ( 12, 16 )	next due: 56
Day 44	R card:2  R= 89.96% grade:3  ivl:111 ( 98, 110)	next due:148
Day 54	R card:1  R= 89.98% grade:3  ivl: 93 ( 86, 98 )	next due:146
Day 56	R card:0  R= 90.26% grade:3  ivl: 30 ( 27, 31 )	next due: 85
```

@user1823, @Expertium, I think it will allow us to discuss the disperse siblings method more clearly. Could you point out the inappropriate schedule of above schedules and provide the desired schedules? I will design the new method based on case by case.

**Comment by L-M-Sherlock** [comment]
```
Day 0	L card:0  R=100.00% grade:1  ivl:  1 (  1, 1  )	next due:  1
Day 1	R card:0  R= 83.98% grade:3  ivl:  3 (  2, 4  )	next due:  4
Day 2	L card:1  R=100.00% grade:2  ivl:  1 (  1, 1  )	next due:  3
Day 3	R card:1  R= 91.79% grade:3  ivl:  3 (  2, 6  )	next due:  7	card:0  delay 1 day
Day 4	L card:2  R=100.00% grade:1  ivl:  1 (  1, 1  )	next due:  5	card:0  delay 1 day
Day 5	R card:2  R= 83.98% grade:3  ivl:  2 (  2, 4  )	next due:  8	card:0  delay 1 day
Day 6	L card:3  R=100.00% grade:1  ivl:  1 (  1, 1  )	next due:  7	card:0  delay 1 day	card:1  delay 1 day
Day 7	R card:3  R= 83.98% grade:3  ivl:  4 (  2, 4  )	next due: 10	card:0  delay 1 day	card:1  delay 1 day	card:2  delay 1 day
Day 9	R card:0  R= 75.74% grade:3  ivl: 13 ( 12, 16 )	next due: 23	card:1  delay 2 day	card:2  delay 2 day	card:3  delay 1 day
Day 11	R card:1  R= 81.81% grade:3  ivl: 20 ( 16, 22 )	next due: 30	card:2  delay 2 day	card:3  delay 2 day
Day 13	R card:2  R= 75.74% grade:3  ivl: 15 ( 12, 16 )	next due: 27	card:3  delay 2 day
Day 15	R card:3  R= 75.74% grade:1  ivl:  1 (  1, 1  )	next due: 16
Day 16	R card:3  R= 91.74% grade:3  ivl:  2 (  2, 2  )	next due: 18
Day 18	R card:3  R= 91.64% grade:3  ivl:  6 (  3, 7  )	next due: 23
Day 23	R card:0  R= 90.15% grade:3  ivl: 33 ( 32, 38 )	next due: 58	card:3  delay 2 day
Day 25	R card:3  R= 86.39% grade:1  ivl:  2 (  2, 2  )	next due: 27
Day 27	R card:2  R= 90.15% grade:3  ivl: 33 ( 32, 38 )	next due: 62	card:3  delay 2 day
Day 29	R card:3  R= 79.65% grade:3  ivl:  6 (  2, 6  )	next due: 33	card:1  delay 1 day
Day 31	R card:1  R= 89.74% grade:3  ivl: 57 ( 50, 58 )	next due: 85
Day 33	R card:3  R= 89.35% grade:3  ivl:  7 (  4, 8  )	next due: 39
Day 39	R card:3  R= 90.32% grade:1  ivl:  2 (  2, 2  )	next due: 41
Day 41	R card:3  R= 88.97% grade:3  ivl:  4 (  2, 4  )	next due: 44
Day 44	R card:3  R= 89.29% grade:3  ivl:  5 (  2, 6  )	next due: 48
Day 48	R card:3  R= 90.93% grade:3  ivl:  8 (  5, 9  )	next due: 55
Day 55	R card:3  R= 90.06% grade:3  ivl: 10 ( 10, 14 )	next due: 67
Day 58	R card:0  R= 89.88% grade:3  ivl: 78 ( 75, 85 )	next due:138
```

I developed a simple method in 37ba83a59c42885f01fd689322461d5352d78bf1 to delay the siblings to prevent them appearing in the next day (except for new cards).

**Comment by user1823** [comment]
> ```py
> if sibling.id != current_card_id and sibling.interval > 0 and sibling.due_date <= today + 1:
>             delay = today + 2 - sibling.due_date
>             sibling.interval += delay
>             sibling.due_date += delay
> ```

This effectively means
```py
if sibling.due_date <= today + 1:
     sibling.due_date = today + 2
```

So, you are just converting a one-day gap into a two-day gap. I don't think that it is good enough.

By the way, I don't think that this issue needs further work. I think that the latest changes in the add-on would be sufficient. However, the actual situation would be clearer in a few more days when @Expertium tests the updated add-on.

**Comment by L-M-Sherlock** [comment]
> So, you are just converting a one-day gap into a two-day gap. I don't think that it is good enough.

Yeah. But even in this case, some cards' retrievability has been significantly lower than the desired retention (75.74% vs 90%). And in this simple method, we only delay necessary siblings. By contrast, in our implementation in the helper add-on, we update all siblings when one of them is reviewed.

**Comment by Expertium** [comment]
I haven't tested the add-on yet, but converting a one day gap into a two day gap is not the proper way to do this. The gap should be a function of interval length (or S).

**Comment by Expertium** [comment]
I just tried using "Disperse all siblings" after updating, and it gave me extra 100 cards. So it can still shorten intervals.

**Comment by user1823** [comment]
Yes, but these should be the ones that would otherwise be due in the next few days. So, it is not as bad as the older version which can make a card due even if it was earlier scheduled an year later.

Shortening the intervals is not actually a problem unless this causes the siblings to be shown very close to each other.

By the way, I recommend talking about the add-on update in the issue present in the add-on repo. Let's keep this issue for simulation of reviews and the related discussion.

**Comment by Expertium** [comment]
@L-M-Sherlock how about this? Make another update to the add-on and make it show two numbers: the number of siblings that have been moved to an earlier date and the number of siblings that have been moved to a later date. That way, I can determine whether most siblings are being moved "backward" or "forward" in time.
Of course, ideally the first number should be 0, but if 5000 siblings have been moved to a later date and 100 have been moved to an earlier date, I can accept that as a valid solution.

**Comment by user1823** [comment]
> That way, I can determine whether most siblings are being moved "backward" or "forward" in time.

> Of course, ideally the second number should be 0

*first

But anyway, it doesn't need to be zero.

Shortening the intervals is not actually a problem unless this causes the siblings to be shown very close to each other.

I don't think that the updated add-on would show siblings very close to each other unless it is very necessary (e.g. they have very short intervals).

You can try using it for a few days (with auto-disperse turned on) and see if you still get siblings at very short intervals from each other. In my opinion, you won't get them unless they have really short stability.

**Comment by user1823** [comment]
By the way, this is what happens if you don't allow cards to be moved "backward" and also don't allow them to move outside their fuzz range.

Posted on 17th September 2023:
> Two cards dispersed but still on the same day as each other:
> 
> - Dispersed card 1339252522910 from 2023-09-27 to 2023-09-27
> - Dispersed card 1676062753446 from 2023-09-27 to 2023-09-27

We don't want to allow cards to be moved outside their fuzz ranges. So, we must allow them to be moved "backward" to prevent such situations.

**Comment by Expertium** [comment]
IIRC we've discussed this before. The idea was to extend the fuzz range only when it's necessary to avoud such a "collision" - siblings being too close to each other. If "collision" is unavoidable, then separate them by some minimal value, like 1 day or 2 days.
To make it more clear:
1) Use 5% fuzz range. If it doesn't cause a collision - great!
2) If it does, use 10% fuzz range. If it doesn't cause a collision - great!
3) If even 10% causes a collision, then make sure that the cards are 1 day apart (or 2 days, whatever is the minimum allowed distance)

**Comment by user1823** [comment]
I have not forgotten about this idea (and I was the one who proposed this idea).

But then, implementing this idea is complicated.

Also, what if I tell you that the current disperse algorithm can separate these cards by scheduling one of them on 24th and one on 27th?

If we had used expanded ranges (10%) without allowing the cards to be moved backward, the due dates would have been 27th and 28th.

So, despite making the ranges larger, the result is less optimal as compared to the current approach.

I agree that there may be a larger separation in _some_ cases. But, the benefit is minimal and the code complexity would increase greatly.

**Comment by Expertium** [comment]
I guess LMSherlock won't like the extra complexity either. Well, for now I'll wait for him to release a new version of the add-on with [these stats](https://github.com/open-spaced-repetition/disperse-siblings-simulator/issues/1#issuecomment-1910234569).

**Comment by L-M-Sherlock** [comment]
> Make another update to the add-on and make it show two numbers: the number of siblings that have been moved to an earlier date and the number of siblings that have been moved to a later date.

Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/disperse-siblings-simulator/files/14071352/fsrs4anki-helper.ankiaddon.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/518be1e35835bc832a1fc4ba18ac2ad80c673d5e

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/disperse-siblings-simulator/assets/83031600/72ab203d-5c9b-4da2-be24-5fb3185c152c)
Here are the numbers. So the ratio of advanced and postponed cards seems to be around 60:40, at least for my collection. I would definitely prefer it to be more in favor of ~~advancing~~ postponing.

**Comment by user1823** [comment]
> I would definitely prefer it to be more in favor of advancing.

*postponing

Advancing = shortening of interval

**Comment by Expertium** [comment]
My bad

**Comment by user1823** [comment]
By the way, are you still seeing siblings on consecutive days?

**Comment by Expertium** [comment]
I'm not sure, I'll keep using it.

**Comment by Expertium** [comment]
Seems like I'm not getting siblings on consecutive days, but I am seeing siblings with a 1 day interval between them, like this:
27.01.2024: Sibling 1
28.01.2024: No siblings
29.01.2024: Sibling 2

**Comment by user1823** [comment]
Can you share their card info?

This shouldn't happen unless
- there is some specific case that we haven't dealt with yet (we have added patches for 4-5 different cases over last several months); or
- there is no scope for dispersing them (e.g. the intervals are too short).

**Comment by L-M-Sherlock** [comment]
The current debugging of dispersing siblings is too inefficient. I plan to implement a log system.

**Comment by Expertium** [comment]
> Can you share their card info?

I found some examples. As you said, it seems like it happens when one of the cards has a short interval.
![Example 1](https://github.com/open-spaced-repetition/disperse-siblings-simulator/assets/83031600/b3d1be32-b82a-44e8-90df-39dbc884d782)

Also, I have a suggestion. Can we make it affect new cards as well? Obviously, new cards don't have intervals yet, but it's possible to change their order to make them appear later. If a sibling gets reviewed, a new card gets pushed further in the queue.

**Comment by user1823** [comment]
The first card in the first pair could have been delayed (because it has a large interval) to prevent the siblings from appearing close to each other. But it wasn't delayed because it already had a low R. (The card was reviewed after 7 months and the next interval ≈ 6.5 m. Unless the weights are very different from the default ones, the R should be below the desired retention.)

At the same time, showing this card too close to its sibling doesn't make sense. You could have forgotten it if it was shown, say, 10 days later.

But if we delay it, there is a possibility that we will need to keep delaying it multiple times because the other card would be reviewed at short intervals.

The conclusion:
None of the situations is ideal. So, we shouldn't change anything (at least for this case).

**Comment by L-M-Sherlock** [comment]
> If a sibling gets reviewed, a new card gets pushed further in the queue.

The problem is how far? And to my best knowledge, the order of new cards has many factors which are set in the preset/deck configuration.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/disperse-siblings-simulator/files/14092284/fsrs4anki-helper.ankiaddon.zip)

The log file is located in the add-on folder. Here is a screenshot of mine.

![image](https://github.com/open-spaced-repetition/disperse-siblings-simulator/assets/32575846/10d53e24-8e28-4240-8094-8d3b2803a98d)

You can search `min_gap: 0` to find siblings who are very close to each others. Note: `min_gap` also considers the latest last review date.

**Comment by user1823** [comment]
@Expertium, note that dispersing all siblings multiple times is not a good idea if you have not rescheduled your cards after updating your parameters or desired retention. (Reason: The cards whose intervals had to be decreased after this change would be moved slightly backward in time towards the ideal interval each time you press Disperse.)

Another reason: It wastes AnkiWeb resources when you sync all those changed cards.

So, I recommend trying this in a separate profile.

**Comment by user1823** [comment]
@Expertium, how is your experience till now? Are you seeing siblings close to each other (except those having a very short interval)?

**Comment by Expertium** [comment]
Nope

**Comment by user1823** [comment]
So, should we close this issue and https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/324?

**Comment by Expertium** [comment]
Wait, I just realized that I haven't tried the new version of the add-on, with the logs.
@L-M-Sherlock There is one card with `min_gap` of 0, but I don't know what's the ID of that card
```
2024-02-03 17:23:28,370 - DEBUG - min_gap: 2, latest_last_review: 1153, today: 1154
2024-02-03 17:23:28,370 - DEBUG - cid: 1698351179790	stability:    2.99	old_due:  1163	new_due:  1163	due_range: [ 1159,  1163]	last_review:  1153
2024-02-03 17:23:28,370 - DEBUG - cid: 1698351179791	stability:   22.47	old_due:  1173	new_due:  1173	due_range: [ 1165,  1173]	last_review:  1107
2024-02-03 17:23:28,370 - DEBUG - cid: 1698351179796	stability:    2.46	old_due:  1159	new_due:  1159	due_range: [ 1156,  1160]	last_review:  1151
2024-02-03 17:23:28,371 - DEBUG - cid: 1698351179802	stability:    4.45	old_due:  1155	new_due:  1155	due_range: [ 1155,  1159]	last_review:  1145
2024-02-03 17:23:28,371 - DEBUG - cid: 1698351179810	stability:    2.94	old_due:  1157	new_due:  1157	due_range: [ 1155,  1159]	last_review:  1149
2024-02-03 17:23:28,379 - DEBUG - min_gap: 0, latest_last_review: 1153, today: 1154
2024-02-03 17:23:28,379 - DEBUG - cid: 1698360210742	stability:    29.9	old_due:  1234	new_due:  1234	due_range: [ 1224,  1234]	last_review:  1147
2024-02-03 17:23:28,379 - DEBUG - cid: 1698360210746	stability:   24.46	old_due:  1178	new_due:  1178	due_range: [ 1170,  1178]	last_review:  1107
2024-02-03 17:23:28,379 - DEBUG - cid: 1698360210752	stability:    8.82	old_due:  1155	new_due:  1155	due_range: [ 1155,  1159]	last_review:  1133
2024-02-03 17:23:28,380 - DEBUG - cid: 1698360210755	stability:    6.01	old_due:  1154	new_due:  1154	due_range: [ 1154,  1154]	last_review:  1135
2024-02-03 17:23:28,380 - DEBUG - cid: 1698360210760	stability:    1.35	old_due:  1159	new_due:  1159	due_range: [ 1155,  1159]	last_review:  1153
2024-02-03 17:23:28,380 - DEBUG - cid: 1698360210762	stability:    1.89	old_due:  1155	new_due:  1155	due_range: [ 1154,  1156]	last_review:  1149
2024-02-03 17:23:28,380 - DEBUG - cid: 1698360210765	stability:    2.36	old_due:  1154	new_due:  1154	due_range: [ 1154,  1154]	last_review:  1146
2024-02-03 17:23:28,380 - DEBUG - cid: 1698360210779	stability:   27.85	old_due:  1196	new_due:  1196	due_range: [ 1186,  1196]	last_review:  1115
2024-02-03 17:23:28,381 - DEBUG - cid: 1698360210780	stability:    9.48	old_due:  1167	new_due:  1167	due_range: [ 1163,  1167]	last_review:  1139
2024-02-03 17:23:28,381 - DEBUG - cid: 1698360210781	stability:    40.4	old_due:  1268	new_due:  1268	due_range: [ 1254,  1268]	last_review:  1150
2024-02-03 17:23:28,393 - DEBUG - min_gap: 1, latest_last_review: 1153, today: 1154
2024-02-03 17:23:28,393 - DEBUG - cid: 1698360747684	stability:     5.8	old_due:  1157	new_due:  1157	due_range: [ 1156,  1162]	last_review:  1143
2024-02-03 17:23:28,393 - DEBUG - cid: 1698360747686	stability:    2.41	old_due:  1156	new_due:  1156	due_range: [ 1155,  1159]	last_review:  1150
2024-02-03 17:23:28,394 - DEBUG - cid: 1698360747687	stability:   25.11	old_due:  1224	new_due:  1224	due_range: [ 1216,  1224]	last_review:  1151
2024-02-03 17:23:28,394 - DEBUG - cid: 1698360747688	stability:    2.28	old_due:  1154	new_due:  1154	due_range: [ 1154,  1155]	last_review:  1147
2024-02-03 17:23:28,394 - DEBUG - cid: 1698360747689	stability:    0.61	old_due:  1155	new_due:  1155	due_range: [ 1155,  1155]	last_review:  1153
2024-02-03 17:23:28,394 - DEBUG - cid: 1698360747690	stability:   26.51	old_due:  1158	new_due:  1158	due_range: [ 1155,  1165]	last_review:  1087
2024-02-03 17:23:28,394 - DEBUG - cid: 1698360747691	stability:   31.21	old_due:  1195	new_due:  1195	due_range: [ 1185,  1195]	last_review:  1104
2024-02-03 17:23:28,395 - DEBUG - cid: 1698360747692	stability:   13.34	old_due:  1165	new_due:  1165	due_range: [ 1159,  1165]	last_review:  1125
```

Or does it mean that multiple cards have `min_gap` of 0? To be honest, I don't know how to read this log

**Comment by L-M-Sherlock** [comment]
> There is one card with min_gap of 0, but I don't know what's the ID of that card

You can search the card in the card browser via cid:xxxxx. 

The series of cards are siblings. Different groups of siblings are separated by the row beginning with min_gap. The min_gap means the minimum interval among siblings and the latest review date.

**Comment by Expertium** [comment]
Do you think it would be more helpful if I just gave you my collection (before dispersing siblings)?

**Comment by user1823** [comment]
> To be honest, I don't know how to read this log

Each line that contains `min_gap` is a heading. The subsequent lines represent cards that are siblings of each other.

After you know this, it should be easy to read the log.

Also, note that `due` is the number of days from the day you started using Anki. In your collection, today's `due` is 1154 (today: 1154).

**Comment by user1823** [comment]
The cards due today are 1698360210755 and 1698360210765. These are the ones with zero gap.  But their stabilities are low, so they can't be dispersed.

**Comment by Expertium** [comment]
But then what about this:
```
2024-02-03 17:23:28,370 - DEBUG - min_gap: 2, latest_last_review: 1153, today: 1154
2024-02-03 17:23:28,370 - DEBUG - cid: 1698351179790	stability:    2.99	old_due:  1163	new_due:  1163	due_range: [ 1159,  1163]	last_review:  1153
2024-02-03 17:23:28,370 - DEBUG - cid: 1698351179791	stability:   22.47	old_due:  1173	new_due:  1173	due_range: [ 1165,  1173]	last_review:  1107
2024-02-03 17:23:28,370 - DEBUG - cid: 1698351179796	stability:    2.46	old_due:  1159	new_due:  1159	due_range: [ 1156,  1160]	last_review:  1151
2024-02-03 17:23:28,371 - DEBUG - cid: 1698351179802	stability:    4.45	old_due:  1155	new_due:  1155	due_range: [ 1155,  1159]	last_review:  1145
2024-02-03 17:23:28,371 - DEBUG - cid: 1698351179810	stability:    2.94	old_due:  1157	new_due:  1157	due_range: [ 1155,  1159]	last_review:  1149
```
It says `min_gap` is 2, but `old_due` and `new_due` are all the same.

**Comment by user1823** [comment]
Old_due is the due date before dispersing.
New_due is after dispersing.

They are same because these cards were already dispersed.

**Comment by Expertium** [comment]
@L-M-Sherlock here's my collection with no media, no text, and before I pressed "Disperse all siblings". I hope this helps!
[Main.zip](https://github.com/open-spaced-repetition/disperse-siblings-simulator/files/14151797/Main.zip)

**Comment by L-M-Sherlock** [comment]
The log has provided enough details. user1832's interpretation is pretty clear.
